project_id = "vudvgfdoeciurejtbzbw"

[functions.generate-script]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.extract-content]
verify_jwt = false

[functions.generate-captions]
verify_jwt = false
